# Remove '#' to select a file or turn off linting.

# Linting with BLACK (Python) enhances code suggestions from LLMs. To disable linting, uncomment the relevant option in the linting settings.

# gpt-engineer can only read selected files. Including irrelevant files will degrade performance, cost additional tokens and potentially overflow token limit.

[linting]
# "linting" = "off"

[files]
# "CLAUDE.md" = "selected"
# "DIANA_ADMIN_ELITE_MASTERPIECE.md" = "selected"
"DIANA_ADMIN_MASTER_DEPLOYMENT_SUMMARY.md" = "selected"
"DIANA_INTEGRATION_COMPLETE.md" = "selected"
# "DMS_temp.py" = "selected"
# "OBLIGADA!/CONEXION_SERVICIOS_REALES_2025-08-09.md" = "selected"
# "OBLIGADA!/INVENTARIO_SERVICIOS.json" = "selected"
# "README.md" = "selected"
# "__init__.py" = "selected"
# "archive-docs/AGENTS.md" = "selected"
# "archive-docs/AGENT_TASKS.md" = "selected"
# "archive-docs/ARCHITECTURE.md" = "selected"
# "archive-docs/Agentes.md" = "selected"
# "archive-docs/CHANNEL_MANAGEMENT_PLAN.md" = "selected"
# "archive-docs/CLAUDE.md" = "selected"
# "archive-docs/DIANA_GAMIFICATION_INTEGRATION.md" = "selected"
# "archive-docs/DIANA_INTEGRATION_COMPLETE_2025-08-07.md" = "selected"
# "archive-docs/GAMIFICATION_INTEGRATION_STATUS.md" = "selected"
# "archive-docs/GEMINI.md" = "selected"
# "archive-docs/IMPLEMENTATION_PLAN.md" = "selected"
# "archive-docs/IMPLEMENTATION_STATUS.md" = "selected"
# "archive-docs/INTEGRATION_STRATEGY.md" = "selected"
# "archive-docs/PROGRESS_UPDATE_2025-07-31.md" = "selected"
# "archive-docs/PROGRESS_UPDATE_2025-07-31_v2.md" = "selected"
# "archive-docs/PROGRESS_UPDATE_EMOTIONAL_SYSTEM_2025-07-31.md" = "selected"
# "archive-docs/PROGRESS_UPDATE_TOKENEITOR_2025-07-31.md" = "selected"
# "archive-docs/PROJECT_MANAGER_REPORT_2025-08-01.md" = "selected"
# "archive-docs/PROJECT_STATUS.md" = "selected"
# "archive-docs/README.md" = "selected"
# "archive-docs/README_DIANA_ADMIN_COMPLETE_OLD.md" = "selected"
# "archive-docs/README_DIANA_COMPLETE_MASTER_OLD.md" = "selected"
# "archive-docs/RESUME_DMS_OLD.md" = "selected"
# "archive-docs/SISTEMA DE ROLEs.md" = "selected"
# "archive-docs/TESTING_STRATEGY.md" = "selected"
# "archive-docs/TOKEN_MANAGEMENT_PLAN.md" = "selected"
# "archive-docs/UNIFIED_PROGRESS.md" = "selected"
# "base_solida.md" = "selected"
# "busca.py" = "selected"
# "busca.py~" = "selected"
# "demo_lucien_admin.py" = "selected"
# "docs/ADMIN_SESSIONS_PERSISTENCIA_TEMPORAL.md" = "selected"
# "docs/ANALISIS_ECOSISTEMA_UNIFICADO.md" = "selected"
# "docs/ARCHIVE.md" = "selected"
# "docs/DIANA_ADMIN_ELITE_TESTING_GUIDE.md" = "selected"
# "docs/DIANA_ADMIN_INTEGRATION_GUIDE.md" = "selected"
# "docs/DIANA_USER_SYSTEM_COMPLETE.md" = "selected"
# "docs/DIANA_USER_TESTING_GUIDE.md" = "selected"
# "docs/DIANA_V2_CALLBACKS_REFERENCE.md" = "selected"
# "docs/DIANA_V2_REFACTOR_SUMMARY.md" = "selected"
# "docs/DOCUMENTATION_GUIDE.md" = "selected"
# "docs/HANDLERS_ARCHITECTURE_GUIDE.md" = "selected"
# "docs/LECTURA OBLIGADA!/ARQUITECTURA_STATUS_CHECK.md" = "selected"
# "docs/LECTURA OBLIGADA!/Conexiones real.md" = "selected"
# "docs/LECTURA OBLIGADA!/INVENTARIO_SERVICIOS.json" = "selected"
# "docs/LECTURA OBLIGADA!/PROXIMO_PASO.md" = "selected"
# "docs/LECTURA OBLIGADA!/QUICK_REFERENCE_SERVICES.md" = "selected"
# "docs/LECTURA OBLIGADA!/SERVICES_INTEGRATION_GUIDE.json" = "selected"
# "docs/LUCIEN_ADMIN_IMPLEMENTATION.md" = "selected"
# "docs/QUICK_START_DIANA_V2.md" = "selected"
# "docs/README.md" = "selected"
# "docs/README_DIANA_ADMIN_COMPLETE.md" = "selected"
# "docs/README_DIANA_COMPLETE_MASTER.md" = "selected"
# "docs/RESUME_DMS.md" = "selected"
# "docs/architecture/00-como-funciona-este-bot.md" = "selected"
# "docs/architecture/01-vision-general.md" = "selected"
# "docs/architecture/02-event-bus.md" = "selected"
# "docs/architecture/03-servicios.md" = "selected"
# "docs/architecture/06-admin-menu-system-analysis.md" = "selected"
# "docs/architecture/07-master-menu-design.md" = "selected"
# "docs/architecture/08-diana-master-system-revolution.md" = "selected"
# "docs/architecture/09-api-reference-diana-master.md" = "selected"
# "docs/architecture/10-diana-master-integration-plan.md" = "selected"
# "docs/architecture/11-diana-master-system-real-services-integration.md" = "selected"
# "docs/architecture/12-diana-admin-elite-masterpiece.md" = "selected"
# "docs/architecture/14-analisis-ecosistema-unificado.md" = "selected"
# "docs/architecture/16-handlers-architecture-guide.md" = "selected"
# "docs/architecture/17-narrativa-elevada.md" = "selected"
# "docs/architecture/CONEXION_SERVICIOS_REALES_2025-08-09.md" = "selected"
# "docs/architecture/DIANA_V2_FINAL_ARCHITECTURE.md" = "selected"
# "docs/architecture/diana-admin-master-system-documentation.md" = "selected"
# "docs/developer-guide/00-quick-start.md" = "selected"
# "docs/developer-guide/01-setup.md" = "selected"
# "docs/developer-guide/02-estructura.md" = "selected"
# "docs/developer-guide/06-system-review-guide.md" = "selected"
# "docs/developer-guide/07-ai-tools-guide.md" = "selected"
# "docs/developer-guide/08-documentation-guide.md" = "selected"
# "docs/developer-guide/09-function-inventory.md" = "selected"
# "docs/developer-guide/DIANA_V2_DEVELOPMENT_GUIDE.md" = "selected"
# "docs/developer-guide/testing/diana-admin.md" = "selected"
# "docs/guia_estilo.md" = "selected"
# "docs/inventario_funciones.md" = "selected"
# "docs/narrativa_elevada.md" = "selected"
# "docs/user-guide/01-introduccion.md" = "selected"
# "docs/user-guide/02-comandos.md" = "selected"
# "docs/¿Cómo funciona este bot? (Estructura general).md" = "selected"
# "examples/diana_integration_example.py" = "selected"
# "fix.sql" = "selected"
"main.py" = "selected"
# "menu_validation_report.json" = "selected"
# nano = "selected"
# "project_structure_no_tests.md" = "selected"
# "pyproject.toml" = "selected"
# "remp_narrativa/diana_validation_client.py" = "selected"
# "remp_narrativa/ejemplo_integracion_diana.py" = "selected"
# "remp_narrativa/funcionalidades.md" = "selected"
# "remp_narrativa/guia_logger.md" = "selected"
# "remp_narrativa/guía.md" = "selected"
# "remp_narrativa/sexy_logger.py" = "selected"
# "remp_narrativa/unificado.md" = "selected"
# "requirements.txt" = "selected"
# "run.sh" = "selected"
# "scripts/README_SCRIPTS.md" = "selected"
# "scripts/diana_interface_showcase.py" = "selected"
# "scripts/generated_data/random_users_20250807_211027.json" = "selected"
# "scripts/populate_random_users.py" = "selected"
# "scripts/quick_demo.py" = "selected"
# "src/__init__.py" = "selected"
# "src/bot/__init__.py" = "selected"
# "src/bot/__main__.py" = "selected"
# "src/bot/config.py" = "selected"
# "src/bot/config/__init__.py" = "selected"
# "src/bot/config/constants.py" = "selected"
# "src/bot/config/settings.py" = "selected"
# "src/bot/core/__init__.py" = "selected"
# "src/bot/core/bootstrap.py" = "selected"
# "src/bot/core/bot.py" = "selected"
# "src/bot/core/containers.py" = "selected"
"src/bot/core/di.py" = "selected"
"src/bot/core/diana_admin_analytics.py" = "selected"
# "src/bot/core/diana_admin_callbacks.py" = "selected"
"src/bot/core/diana_admin_master.py" = "selected"
# "src/bot/core/diana_admin_security.py" = "selected"
# "src/bot/core/diana_admin_services_integration.py" = "selected"
# "src/bot/core/diana_core_system.py" = "selected"
# "src/bot/core/diana_master_system.py" = "selected"
# "src/bot/core/diana_user_master_system.py" = "selected"
# "src/bot/core/errors.py" = "selected"
"src/bot/core/handlers.py" = "selected"
# "src/bot/core/middleware.py" = "selected"
# "src/bot/core/orchestrator.py" = "selected"
# "src/bot/core/scheduler.py" = "selected"
# "src/bot/database/__init__.py" = "selected"
# "src/bot/database/base.py" = "selected"
# "src/bot/database/bot.db" = "selected"
# "src/bot/database/data_injection.py" = "selected"
# "src/bot/database/engine.py" = "selected"
# "src/bot/database/models/__init__.py" = "selected"
# "src/bot/database/models/admin.py" = "selected"
# "src/bot/database/models/channel.py" = "selected"
# "src/bot/database/models/emotional.py" = "selected"
# "src/bot/database/models/gamification.py" = "selected"
# "src/bot/database/models/narrative.py" = "selected"
# "src/bot/database/models/token.py" = "selected"
# "src/bot/database/models/user.py" = "selected"
# "src/bot/filters/__init__.py" = "selected"
# "src/bot/filters/is_admin.py" = "selected"
# "src/bot/filters/role.py" = "selected"
"src/bot/handlers/gamification/__init__.py" = "selected"
"src/bot/handlers/gamification/misiones.py" = "selected"
"src/bot/handlers/gamification/progress.py" = "selected"
# "src/bot/handlers/narrative/__init__.py" = "selected"
# "src/bot/handlers/narrative/mochila.py" = "selected"
# "src/bot/handlers/narrative/navigation.py" = "selected"
# "src/bot/handlers/user/__init__.py" = "selected"
# "src/bot/handlers/user/daily_rewards.py" = "selected"
# "src/bot/handlers/user/help.py" = "selected"
# "src/bot/handlers/user/info.py" = "selected"
# "src/bot/handlers/user/profile.py" = "selected"
# "src/bot/handlers/user/shop.py" = "selected"
# "src/bot/handlers/user/start.py" = "selected"
# "src/bot/handlers/user/token_redemption.py" = "selected"
# "src/bot/handlers/user/trivia.py" = "selected"
# "src/bot/keyboards/__init__.py" = "selected"
# "src/bot/keyboards/keyboard_factory.py" = "selected"
# "src/bot/keyboards/keyboard_factory.py~" = "selected"
# "src/bot/listeners/__init__.py" = "selected"
# "src/bot/listeners/mission_listener.py" = "selected"
# "src/bot/middlewares/__init__.py" = "selected"
# "src/bot/middlewares/admin.py" = "selected"
# "src/bot/middlewares/database.py" = "selected"
# "src/bot/middlewares/emotional.py" = "selected"
# "src/bot/middlewares/points.py" = "selected"
# "src/bot/middlewares/role.py" = "selected"
# "src/bot/middlewares/throttling.py" = "selected"
# "src/bot/middlewares/user.py" = "selected"
# "src/bot/services/__init__.py" = "selected"
"src/bot/services/admin.py" = "selected"
# "src/bot/services/base.py" = "selected"
# "src/bot/services/emotional.py" = "selected"
"src/bot/services/gamification.py" = "selected"
# "src/bot/services/narrative.py" = "selected"
# "src/bot/services/role.py" = "selected"
# "src/bot/services/user.py" = "selected"
"src/bot/tasks/role_maintenance.py" = "selected"
# "src/bot/tasks/subscription.py" = "selected"
# "src/conector_servicios.py" = "selected"
# "src/core/__init__.py" = "selected"
"src/core/event_bus.py" = "selected"
# "src/core/interfaces/ICoreService.py" = "selected"
# "src/core/interfaces/IEventBus.py" = "selected"
# "src/core/services/__init__.py" = "selected"
# "src/core/services/config.py" = "selected"
"src/diana_admin_master.py" = "selected"
# "src/infrastructure/__init__.py" = "selected"
# "src/infrastructure/telegram/adapter.py" = "selected"
# "src/infrastructure/telegram/listener.py" = "selected"
# "src/modules/__init__.py" = "selected"
# "src/modules/admin/README.md" = "selected"
# "src/modules/admin/service.py" = "selected"
# "src/modules/channel/__init__.py" = "selected"
# "src/modules/channel/events.py" = "selected"
# "src/modules/channel/service.py" = "selected"
# "src/modules/daily_rewards/__init__.py" = "selected"
# "src/modules/daily_rewards/service.py" = "selected"
# "src/modules/emotional/__init__.py" = "selected"
# "src/modules/emotional/diana_state.py" = "selected"
# "src/modules/emotional/events.py" = "selected"
# "src/modules/emotional/middleware.py" = "selected"
# "src/modules/emotional/service.py" = "selected"
# "src/modules/events.py" = "selected"
# "src/modules/gamification/README.md" = "selected"
# "src/modules/gamification/__init__.py" = "selected"
# "src/modules/gamification/diana_missions.py" = "selected"
# "src/modules/gamification/service.py" = "selected"
# "src/modules/narrative/README.md" = "selected"
# "src/modules/narrative/__init__.py" = "selected"
# "src/modules/narrative/diana_integration.py" = "selected"
# "src/modules/narrative/service.py" = "selected"
# "src/modules/shop/__init__.py" = "selected"
# "src/modules/shop/service.py" = "selected"
# "src/modules/tariff/__init__.py" = "selected"
# "src/modules/tariff/service.py" = "selected"
# "src/modules/token/__init__.py" = "selected"
# "src/modules/token/events.py" = "selected"
# "src/modules/token/tokeneitor.py" = "selected"
# "src/modules/trivia/__init__.py" = "selected"
# "src/modules/trivia/service.py" = "selected"
# "src/modules/user/service.py" = "selected"
# "src/servicio.py" = "selected"
# "src/servicio_manager.py" = "selected"
# "src/utils/__init__.py" = "selected"
# "src/utils/sexy_logger.py" = "selected"
# "validate_diana_admin_system.py" = "selected"
# 